# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
#       - name: List Current Directory
#         run: ls -a

#       - name: List in Target Folder
#         run:  |
#           cd target
#           ls -a
          
      - name: Test with Maven Part 1
        run: mvn clean test

      - name: Test with Maven
        run: mvn -B package --file pom.xml test
        
      - name: Build
        run: mvn --batch-mode -DskipTests package

#       - name: Test
#         run: mvn --batch-mode -Dmaven.test.failure.ignore=true test  
        
      - name: Test Reporter
        uses: dorny/test-reporter@v1.4.3
        with:
           name: Run Tests
           path: "target/surefire-reports/junitreports/TEST-*.xml"
           reporter: java-junit
           
